# Generated by Django 5.0.6 on 2024-07-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tshirt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.CharField(max_length=50)),
                ("height", models.FloatField()),
                ("weight", models.FloatField()),
                ("color_of_tshirt", models.CharField(max_length=50)),
                ("size_of_tshirt", models.CharField(max_length=10)),
                ("price", models.FloatField()),
            ],
        ),
    ]
